Digipost\Signature\API\XML\Thirdparty\ASiCe\XAdESSignaturesType:
    properties:
        signature:
            expose: true
            access_type: public_method
            accessor:
                getter: getSignature
                setter: setSignature
            xml_map:
                inline: true
                entry_name: Signature
                namespace: 'http://uri.etsi.org/2918/v1.2.1#'
            type: array<Digipost\Signature\API\XML\Thirdparty\XMLdSig\Signature>
