Digipost\Signature\API\XML\Thirdparty\XMLdSig\KeyName:
    xml_root_name: KeyName
    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
