Digipost\Signature\API\XML\Thirdparty\XMLdSig\ManifestType:
    properties:
        id:
            expose: true
            access_type: public_method
            serialized_name: Id
            accessor:
                getter: getId
                setter: setId
            xml_attribute: true
            type: string
        reference:
            expose: true
            access_type: public_method
            serialized_name: Reference
            accessor:
                getter: getReference
                setter: setReference
            xml_list:
                inline: true
                entry_name: Reference
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            type: array<Digipost\Signature\API\XML\Thirdparty\XMLdSig\Reference>
