Digipost\Signature\API\XML\Thirdparty\XMLdSig\PGPDataType:
    properties:
        pGPKeyID:
            expose: true
            access_type: public_method
            serialized_name: PGPKeyID
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getPGPKeyID
                setter: setPGPKeyID
            type: Digipost\Signature\API\XML\CustomBase64BinaryType
        pGPKeyPacket:
            expose: true
            access_type: public_method
            serialized_name: PGPKeyPacket
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getPGPKeyPacket
                setter: setPGPKeyPacket
            type: Digipost\Signature\API\XML\CustomBase64BinaryType
