Digipost\Signature\API\XML\Thirdparty\XMLdSig\SPKIDataType:
    properties:
        sPKISexp:
            expose: true
            access_type: public_method
            serialized_name: SPKISexp
            accessor:
                getter: getSPKISexp
                setter: setSPKISexp
            xml_list:
                inline: true
                entry_name: SPKISexp
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            type: array<Digipost\Signature\API\XML\CustomBase64BinaryType>
