Digipost\Signature\API\XML\Thirdparty\XMLdSig\X509DataType:
    properties:
        x509IssuerSerial:
            expose: true
            access_type: public_method
            serialized_name: X509IssuerSerial
            accessor:
                getter: getX509IssuerSerial
                setter: setX509IssuerSerial
            xml_list:
                inline: true
                entry_name: X509IssuerSerial
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            type: array<Digipost\Signature\API\XML\Thirdparty\XMLdSig\X509IssuerSerialType>
        x509SKI:
            expose: true
            access_type: public_method
            serialized_name: X509SKI
            accessor:
                getter: getX509SKI
                setter: setX509SKI
            xml_list:
                inline: true
                entry_name: X509SKI
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            type: array<Digipost\Signature\API\XML\CustomBase64BinaryType>
        x509SubjectName:
            expose: true
            access_type: public_method
            serialized_name: X509SubjectName
            accessor:
                getter: getX509SubjectName
                setter: setX509SubjectName
            xml_list:
                inline: true
                entry_name: X509SubjectName
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            type: array<string>
        x509Certificate:
            expose: true
            access_type: public_method
            serialized_name: X509Certificate
            accessor:
                getter: getX509Certificate
                setter: setX509Certificate
            xml_map:
                inline: true
                entry_name: X509Certificate
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            type: array<Digipost\Signature\API\XML\CustomBase64BinaryType>
        x509CRL:
            expose: true
            access_type: public_method
            serialized_name: X509CRL
            accessor:
                getter: getX509CRL
                setter: setX509CRL
            xml_list:
                inline: true
                entry_name: X509CRL
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            type: array<Digipost\Signature\API\XML\CustomBase64BinaryType>
