Digipost\Signature\API\XML\Thirdparty\XAdES\CertIDType:
    properties:
        uRI:
            expose: true
            access_type: public_method
            serialized_name: URI
            accessor:
                getter: getURI
                setter: setURI
            xml_attribute: true
            type: string
        certDigest:
            expose: true
            access_type: public_method
            serialized_name: CertDigest
            xml_element:
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getCertDigest
                setter: setCertDigest
            type: Digipost\Signature\API\XML\Thirdparty\XAdES\DigestAlgAndValueType
        issuerSerial:
            expose: true
            access_type: public_method
            serialized_name: IssuerSerial
            xml_element:
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getIssuerSerial
                setter: setIssuerSerial
            type: Digipost\Signature\API\XML\Thirdparty\XMLdSig\X509IssuerSerialType
