Digipost\Signature\API\XML\Thirdparty\XAdES\CertIDListType:
    properties:
        cert:
            expose: true
            access_type: public_method
            serialized_name: Cert
            accessor:
                getter: getCert
                setter: setCert
            xml_list:
                inline: true
                entry_name: Cert
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            type: array<Digipost\Signature\API\XML\Thirdparty\XAdES\CertIDType>
