Digipost\Signature\API\XML\Thirdparty\XAdES\CounterSignatureType:
    properties:
        signature:
            expose: true
            access_type: public_method
            serialized_name: Signature
            xml_element:
                namespace: 'http://www.w3.org/2000/09/xmldsig#'
            accessor:
                getter: getSignature
                setter: setSignature
            type: Digipost\Signature\API\XML\Thirdparty\XMLdSig\Signature
