Digipost\Signature\API\XML\Thirdparty\XAdES\ObjectIdentifierType:
    properties:
        identifier:
            expose: true
            access_type: public_method
            serialized_name: Identifier
            xml_element:
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getIdentifier
                setter: setIdentifier
            type: Digipost\Signature\API\XML\Thirdparty\XAdES\IdentifierType
        description:
            expose: true
            access_type: public_method
            serialized_name: Description
            xml_element:
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getDescription
                setter: setDescription
            type: string
        documentationReferences:
            expose: true
            access_type: public_method
            serialized_name: DocumentationReferences
            xml_element:
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getDocumentationReferences
                setter: setDocumentationReferences
            type: array<string>
            xml_list:
                inline: false
                entry_name: DocumentationReference
                skip_when_empty: true
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
