Digipost\Signature\API\XML\Thirdparty\XAdES\SPURI:
    xml_root_name: SPURI

    properties:
        __value:
            expose: true
            xml_value: true
            access_type: public_method
            accessor:
                getter: value
                setter: value
            type: string
