Digipost\Signature\API\XML\Thirdparty\XAdES\SPUserNoticeType:
    properties:
        noticeRef:
            expose: true
            access_type: public_method
            serialized_name: NoticeRef
            xml_element:
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getNoticeRef
                setter: setNoticeRef
            type: Digipost\Signature\API\XML\Thirdparty\XAdES\NoticeReferenceType
        explicitText:
            expose: true
            access_type: public_method
            serialized_name: ExplicitText
            xml_element:
                namespace: 'http://uri.etsi.org/01903/v1.3.2#'
            accessor:
                getter: getExplicitText
                setter: setExplicitText
            type: string
