services:
  _defaults:
    autowire: true
    public: true
    autoconfigure: false

  digipost_signature.event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher

  digipost_signature.keystore_file_loader:
    class: Digipost\Signature\Loader\KeyStoreFileLoader
    factory: ['Digipost\Signature\Loader\KeyStoreFileLoader', loader]
    arguments: ['@service_container', '%digipost_signature.keystore.filename%']

  digipost_signature.keystore_config:
    class: Digipost\Signature\Client\Security\KeyStoreConfig
    factory: ['Digipost\Signature\Client\Security\KeyStoreConfig', fromKeyStoreFileLoader]
    arguments:
      - '@digipost_signature.keystore_file_loader'
      - '%digipost_signature.keystore.key.alias%'
      - '%digipost_signature.keystore.password%'
      - '%digipost_signature.keystore.key.password%'

  digipost_signature.keystore:
    class: Digipost\Signature\Client\Core\Internal\Security\KeyStore
    autowire: false
    calls:
      - [initFromFile, ['@digipost_signature.keystore_file_loader', '%digipost_signature.keystore.password%', '%digipost_signature.keystore.key.password%']]

  digipost_signature.client_guzzle_config:
    class: Digipost\Signature\Client\Core\Internal\Http\ClientGuzzleConfig
    factory: ['Digipost\Signature\Client\Core\Internal\Http\ClientGuzzleConfig', factory]
    autowire: false
    arguments: ['@service_container', '@digipost_signature.event_dispatcher']

  digipost_signature.certificate_trust_strategy:
    class: Digipost\Signature\Client\Core\Internal\Http\PostenEnterpriseCertificateStrategy
    autowire: false
    arguments: ['@digipost_signature.keystore', '@digipost_signature.event_dispatcher']

  digipost_signature.client_configuration_builder:
    class: Digipost\Signature\Client\ClientConfigurationBuilder
    factory: 'Digipost\Signature\Client\ClientConfiguration::builder'
    autowire: false
    arguments:
      - '@service_container'
      - '@digipost_signature.keystore_config'
      - '@digipost_signature.event_dispatcher'

  digipost_signature.client_helper:
    class: Digipost\Signature\Client\Core\Internal\ClientHelper
    autowire: false
    arguments:
      ['@?', '@?']
    calls:
      - [setLogger, ['@?logger']]

  digipost_signature.client_configuration:
    class: Digipost\Signature\Client\ClientConfiguration
    factory_service: 'Digipost\Signature\Client\ClientConfigurationBuilder'
    autowire: false
    arguments:
      - '@digipost_signature.keystore_config'
      - '@digipost_signature.client_guzzle_config'
      - '@digipost_signature.event_dispatcher'

  digipost_signature.xml_marshaller:
    class: Digipost\Signature\Client\Core\Internal\XML\Marshalling
    factory: ['Digipost\Signature\Client\Core\Internal\XML\Marshalling', factory]
    autowire: false
    autoconfigure: false
    arguments:
      - '@service_container'

  digipost_signature.xml_signature_factory:
    class: Digipost\Signature\Client\Core\Internal\XMLSignatureFactory
    arguments:
      ['@service_container']

  digipost_signature.xml_signature_context:
    class: Digipost\Signature\Client\Core\Internal\XMLDigitalSignatureContext
    factory: ['Digipost\Signature\Client\Core\Internal\XMLDigitalSignatureContext', factory]
    arguments: ['@service_container', '@sabre_io.xml.service']

  digipost_signature.asice.document_bundle_dumper:
    class: Digipost\Signature\Client\ASiCe\DumpDocumentBundleToDisk
    factory: ['Digipost\Signature\Client\ASiCe\DumpDocumentBundleToDisk', factory]
    autowire: false
    arguments: ['@service_container']

  digipost_signature.locate_resource:
    factory_service: kernel
    factory_method: locateResource
    synthetic: true

  digipost_signature.client_certificates:
    class: Digipost\Signature\Client\Certificates
    factory: ['Digipost\Signature\Client\Certificates', build]
    autowire: false
    arguments: ['@service_container', '%digipost_signature.keystore.ca_path%']

  sabre_io.xml.service:
    class: Sabre\Xml\Service
